openapi: 3.0.0
info:
  title: Category API
  version: "1.0.0"
paths:
  /category:
    get:
      tags: [Category]
      summary: Retrieve paginated list of categories
      description: >
        Retrieves a list of categories. Supports pagination via "page" and "limit" query parameters.
      parameters:
        - in: query
          name: page
          schema:
            type: number
          description: Page number (default is 1)
        - in: query
          name: limit
          schema:
            type: number
          description: Items per page (default is 10)
      responses:
        "200":
          description: A list of categories retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Categories retrieved successfully"
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "cat123"
                        name:
                          type: string
                          example: "Electronics"
    post:
      tags: [Category]
      summary: Create a new category
      description: Creates a new category requiring a unique name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Category created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Category created successfully"
                  category:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "cat123"
                      name:
                        type: string
                        example: "Electronics"
  /category/{id}:
    get:
      tags: [Category]
      summary: Retrieve a category by ID
      description: Retrieves category details by its unique identifier.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the category.
      responses:
        "200":
          description: Category details retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Category retrieved successfully"
                  category:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "cat123"
                      name:
                        type: string
                        example: "Electronics"
    patch:
      tags: [Category]
      summary: Update an existing category
      description: Updates the name of an existing category.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the category to update.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "200":
          description: Category updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Category updated successfully"
                  category:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "cat123"
                      name:
                        type: string
                        example: "Updated Electronics"
    delete:
      tags: [Category]
      summary: Delete a category by ID
      description: Deletes the specified category.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the category to delete.
      responses:
        "200":
          description: Category deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Category deleted successfully"
