paths:
  /order:
    get:
      tags: [Order]
      summary: Retrieve paginated list of orders
      parameters:
        - in: query
          name: page
          schema:
            type: number
          description: Page number
        - in: query
          name: limit
          schema:
            type: number
          description: Items per page
      responses:
        "200":
          description: A list of orders
    post:
      tags: [Order]
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              # ... order properties schema ...
      responses:
        "201":
          description: Order created successfully
  /order/{id}:
    get:
      tags: [Order]
      summary: Retrieve an order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order details retrieved successfully
    patch:
      tags: [Order]
      summary: Update an order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              # ... updatable order properties schema ...
      responses:
        "200":
          description: Order updated successfully
    delete:
      tags: [Order]
      summary: Delete an order by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order deleted successfully
