paths:
  /product:
    get:
      summary: Retrieve paginated list of products
      parameters:
        - in: query
          name: page
          schema:
            type: number
          description: Page number
        - in: query
          name: limit
          schema:
            type: number
          description: Items per page
      responses:
        "200":
          description: A list of products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Products retrieved successfully"
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "prod123"
                        name:
                          type: string
                          example: "Sample Product"
                        description:
                          type: string
                          example: "Detailed product description"
                        price:
                          type: number
                          example: 99.99
                        stock:
                          type: number
                          example: 100
                        categoryId:
                          type: string
                          example: "cat123"
                        images:
                          type: array
                          items:
                            type: object
                            properties:
                              url:
                                type: string
                                example: "/uploads/12345.png"
                              imageOrder:
                                type: number
                                example: 1
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product name
                  example: "New Product"
                description:
                  type: string
                  description: Product description
                  example: "Detailed description of product"
                price:
                  type: number
                  description: Product price
                  example: 99.99
                stock:
                  type: number
                  description: Available stock
                  example: 100
                categoryId:
                  type: string
                  description: Category identifier
                  example: "cat123"
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Array of product images
              required:
                - name
                - description
                - price
                - stock
                - categoryId
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product created successfully"
                  product:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "prod123"
                      name:
                        type: string
                        example: "New Product"
                      description:
                        type: string
                        example: "Detailed description of product"
                      price:
                        type: number
                        example: 99.99
                      stock:
                        type: number
                        example: 100
                      categoryId:
                        type: string
                        example: "cat123"
                      images:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: "/uploads/12345.png"
                            imageOrder:
                              type: number
                              example: 1
  /product/{id}:
    get:
      summary: Retrieve a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product identifier
      responses:
        "200":
          description: Product details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product retrieved successfully"
                  product:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "prod123"
                      name:
                        type: string
                        example: "Sample Product"
                      description:
                        type: string
                        example: "Product detailed description"
                      price:
                        type: number
                        example: 99.99
                      stock:
                        type: number
                        example: 100
                      categoryId:
                        type: string
                        example: "cat123"
                      images:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: "/uploads/12345.png"
                            imageOrder:
                              type: number
                              example: 1
    patch:
      summary: Update an existing product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product identifier
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Updated product name
                description:
                  type: string
                  description: Updated product description
                price:
                  type: number
                  description: Updated price
                stock:
                  type: number
                  description: Updated stock count
                categoryId:
                  type: string
                  description: Updated category identifier
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: New product images to add
                removedImageIds:
                  type: array
                  items:
                    type: string
                  description: IDs of images to remove
                imagesOrder:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      order:
                        type: number
                  description: New order for product images
      responses:
        "200":
          description: Product updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product updated successfully"
                  product:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "prod123"
                      name:
                        type: string
                        example: "Updated Product"
                      description:
                        type: string
                        example: "Updated product description"
                      price:
                        type: number
                        example: 89.99
                      stock:
                        type: number
                        example: 150
                      categoryId:
                        type: string
                        example: "cat123"
                      images:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: "/uploads/updated.png"
                            imageOrder:
                              type: number
                              example: 2
    delete:
      summary: Delete a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product identifier
      responses:
        "200":
          description: Product deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product deleted successfully"
