paths:
  /review:
    get:
      summary: Retrieve paginated list of reviews
      parameters:
        - in: query
          name: page
          schema:
            type: number
        - in: query
          name: limit
          schema:
            type: number
      responses:
        "200":
          description: A list of reviews
    post:
      summary: Create a new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                productId:
                  type: string
                rating:
                  type: number
                comment:
                  type: string
              required:
                - userId
                - productId
                - rating
                - comment
      responses:
        "201":
          description: Review created successfully
  /review/{id}:
    get:
      summary: Retrieve a review by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Review details retrieved successfully
    patch:
      summary: Update an existing review
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: number
                comment:
                  type: string
      responses:
        "200":
          description: Review updated successfully
    delete:
      summary: Delete a review by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Review deleted successfully
