openapi: 3.0.0
info:
  title: Ecommerce API
  version: "1.0.0"
  description: API documentation for the Ecommerce application
servers:
  - url: http://localhost:5000/v1
paths:
  /auth/register:
    $ref: "./auth.yaml#/paths/~1auth~1register"
  /auth/login:
    $ref: "./auth.yaml#/paths/~1auth~1login"
  /auth/refresh:
    $ref: "./auth.yaml#/paths/~1auth~1refresh"
  /auth/logout:
    $ref: "./auth.yaml#/paths/~1auth~1logout"
  /auth/lost-email:
    $ref: "./auth.yaml#/paths/~1auth~1lost-email"
  /auth/lost-code:
    $ref: "./auth.yaml#/paths/~1auth~1lost-code"
  /user:
    $ref: "./user.yaml#/paths/~1user"
  /user/{id}:
    $ref: "./user.yaml#/paths/~1user~1{id}"
  /order:
    $ref: "./order.yaml#/paths/~1order"
  /order/{id}:
    $ref: "./order.yaml#/paths/~1order~1{id}"
  /cart:
    $ref: "./cart.yaml#/paths/~1cart"
  /cart/item:
    $ref: "./cart.yaml#/paths/~1cart~1item"
  /cart/item/{id}:
    $ref: "./cart.yaml#/paths/~1cart~1item~1{id}"
  /cart/clear:
    $ref: "./cart.yaml#/paths/~1cart~1clear"
  /category:
    $ref: "./category.yaml#/paths/~1category"
  /category/{id}:
    $ref: "./category.yaml#/paths/~1category~1{id}"
  /product:
    $ref: "./product.yaml#/paths/~1product"
  /product/{id}:
    $ref: "./product.yaml#/paths/~1product~1{id}"
  /review:
    $ref: "./review.yaml#/paths/~1review"
  /review/{id}:
    $ref: "./review.yaml#/paths/~1review~1{id}"
  /payment:
    $ref: "./payment.yaml#/paths/~1payment"
  /payment/{id}:
    $ref: "./payment.yaml#/paths/~1payment~1{id}"
