openapi: 3.0.0
info:
  title: User API
  version: "1.0.0"
paths:
  /user:
    get:
      tags: [User]
      summary: Retrieve paginated list of users
      parameters:
        - in: query
          name: page
          schema:
            type: number
          description: Page number
        - in: query
          name: limit
          schema:
            type: number
          description: Items per page
      responses:
        "200":
          description: A list of users
    post:
      tags: [User]
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              # ... user properties schema ...
      responses:
        "201":
          description: User created successfully
  /user/{id}:
    get:
      tags: [User]
      summary: Retrieve a user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User details retrieved successfully
    patch:
      tags: [User]
      summary: Update an existing user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              # ... updatable user properties schema ...
      responses:
        "200":
          description: User updated successfully
    delete:
      tags: [User]
      summary: Delete a user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
